const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const appDir = path.join(root, 'android-app');

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

const packageJson = JSON.parse(fs.readFileSync(path.join(appDir, 'package.json'), 'utf8'));
const capConfig = JSON.parse(fs.readFileSync(path.join(appDir, 'capacitor.config.json'), 'utf8'));
const prepareReleaseScript = fs.readFileSync(path.join(appDir, 'scripts/prepare-release-webdir.js'), 'utf8');
const gitignore = fs.readFileSync(path.join(root, '.gitignore'), 'utf8');
const appBuildGradle = fs.readFileSync(path.join(appDir, 'android/app/build.gradle'), 'utf8');
const mainActivity = fs.readFileSync(path.join(appDir, 'android/app/src/main/java/io/quotedr/app/MainActivity.java'), 'utf8');
const invoiceViewer = fs.readFileSync(path.join(root, 'invoice-viewer.html'), 'utf8');
const quoteBuilder = fs.readFileSync(path.join(root, 'quote-builder.html'), 'utf8');
const settings = fs.readFileSync(path.join(root, 'settings.html'), 'utf8');

assert(packageJson.name === 'quotedr-android-app', 'package should identify the full QuoteDr Android app');
assert(packageJson.scripts.sync === 'npx cap sync android', 'package should expose Capacitor Android sync');
assert(packageJson.scripts['prepare:release'] === 'node scripts/prepare-release-webdir.js', 'package should prepare bundled QuoteDr web assets for release');
assert(packageJson.scripts['sync:release'].includes('prepare:release'), 'release sync should prepare web assets before Capacitor sync');
assert(packageJson.scripts['build:aab'].includes('bundleRelease'), 'package should expose an Android App Bundle build script');
assert(packageJson.scripts.check === 'node --check scripts/prepare-release-webdir.js', 'clean checkouts should validate the tracked release generator without requiring generated www output');
assert(capConfig.appId === 'io.quotedr.app', 'full app should use the QuoteDr Android app id');
assert(capConfig.appName === 'QuoteDr', 'full app should use the QuoteDr app name');
assert(capConfig.webDir === 'www', 'full app should serve the launcher from www');
assert(!capConfig.server.url, 'Play builds must not point at a local development server');
assert(capConfig.server.androidScheme === 'https', 'bundled app should use Capacitor local https scheme');
assert(prepareReleaseScript.includes('dashboard.html'), 'release web assets should open the QuoteDr dashboard');
assert(prepareReleaseScript.includes('copyDirectories'), 'release preparation should copy app asset directories');
assert(prepareReleaseScript.includes("'.env.local'"), 'release preparation should exclude local environment files');
assert(gitignore.split(/\r?\n/).includes('android-app/www/'), 'generated Android www output should remain ignored');
assert(appBuildGradle.includes('keystore.properties'), 'release build should support an ignored local signing config');
assert(appBuildGradle.includes('signingConfigs'), 'release build should define a signing config');
assert(appBuildGradle.includes('bundleRelease') === false, 'Gradle file should not hard-code bundle task names');
assert(prepareReleaseScript.includes('QuoteDr is opening'), 'generated launcher should show a loading state');
assert(prepareReleaseScript.includes('@capacitor/app'), 'generated launcher should use Capacitor App plugin');
assert(prepareReleaseScript.includes('App.addListener('), 'generated launcher should wire native app events');
assert(prepareReleaseScript.includes("window.location.replace('dashboard.html')"), 'generated launcher should open the bundled QuoteDr dashboard');
assert(mainActivity.includes('enableImmersiveMode'), 'Android app should hide the navigation bar in immersive mode');
assert(mainActivity.includes('WindowInsets.Type.statusBars() | WindowInsets.Type.navigationBars()'), 'Android app should hide status and navigation bars together');
assert(mainActivity.includes('BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE'), 'Android app should reveal hidden bars with a swipe');
assert(mainActivity.includes('SYSTEM_UI_FLAG_IMMERSIVE_STICKY'), 'Android app should support immersive sticky mode on older Android versions');
assert(mainActivity.includes('SYSTEM_UI_FLAG_FULLSCREEN'), 'Android app should hide the status bar on older Android versions');
assert(mainActivity.includes('SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN'), 'Android app should reserve edge-to-edge status bar behavior on older Android versions');
assert(mainActivity.includes('addJavascriptInterface'), 'Android app should expose a native bridge to web pages');
assert(mainActivity.includes('QuoteDrAndroid'), 'Android app should expose the QuoteDrAndroid JavaScript interface');
assert(mainActivity.includes('setWebViewClient'), 'Android app should patch WebView pages after navigation');
assert(mainActivity.includes('window.print = function()'), 'Android app should route existing window.print calls to native printing');
assert(mainActivity.includes('PrintManager'), 'Android app should use Android PrintManager for WebView printing');
assert(mainActivity.includes('createPrintDocumentAdapter'), 'Android app should create a WebView print document adapter');
assert(invoiceViewer.includes('invoice-amount-cell'), 'invoice viewer should mark money cells for portrait wrapping control');
assert(invoiceViewer.includes('white-space: nowrap;'), 'invoice viewer should keep amount cells on one line');
assert(invoiceViewer.includes('.invoice-business-info-grid'), 'invoice viewer should use a compact business info grid on portrait phones');
assert(invoiceViewer.includes('@media (max-width: 575.98px)'), 'invoice viewer should have phone portrait layout rules');
assert(invoiceViewer.includes('function printInvoice()'), 'invoice viewer should route print actions through a helper');
assert(invoiceViewer.includes('QuoteDrAndroid.printCurrentPage'), 'invoice viewer should call the native Android print bridge when available');
assert(invoiceViewer.includes('onclick="printInvoice()"'), 'invoice viewer print button should use the native-aware print helper');
assert(quoteBuilder.includes('quote-actions-dropdown'), 'quote builder should mark the Quote Actions dropdown for mobile layout fixes');
assert(quoteBuilder.includes('quote-actions-menu'), 'quote builder should mark the Quote Actions menu for mobile layout fixes');
assert(quoteBuilder.includes('max-width: calc(100vw - 1.5rem)'), 'quote actions menu should stay inside the phone viewport');
assert(quoteBuilder.includes('overflow-wrap: anywhere'), 'quote actions menu item text should stay inside the dropdown panel');
assert(quoteBuilder.includes('autosave-toolbar-toggle'), 'quote builder should mark the autosave toolbar control for mobile layout');
assert(quoteBuilder.includes('#autoSaveToggle + .form-check-label { display: inline-block !important; }'), 'autosave label should stay visible on mobile');
assert(!quoteBuilder.includes('#autoSaveToggle + .form-check-label { display: none !important; }'), 'autosave label should not be hidden on mobile');
assert(quoteBuilder.includes('syncMobileActionBarVisibility'), 'quote builder should keep the mobile action bar visible while scrolling');
assert(quoteBuilder.includes('mobile-action-bar-hidden'), 'quote builder should hide the mobile action bar only near the page bottom');
assert(quoteBuilder.includes('env(safe-area-inset-bottom'), 'mobile action bar should respect device safe-area bottom insets');
assert(quoteBuilder.includes('quote-identity-grid'), 'quote builder should group quote number, title, and status in a clear identity grid');
assert(quoteBuilder.includes('quote-number-heading'), 'quote number actions should live in the quote number heading row');
assert(quoteBuilder.includes('quote-number-actions'), 'randomize and next buttons should be visually attached to quote number');
assert(quoteBuilder.indexOf('quote-number-actions') < quoteBuilder.indexOf('quoteTitle'), 'quote number actions should appear before the file name field');
assert(quoteBuilder.includes('settings.html?tab=quotes&section=terms'), 'manage terms link should open the Quotes settings terms section');
assert(quoteBuilder.includes('savedTerms.length'), 'quote builder should ignore empty custom terms and fall back to built-ins');
assert(settings.includes('id="quoteTermsSettings"'), 'settings terms card should have a direct anchor target');
assert(settings.includes('DEFAULT_QUOTE_TERMS'), 'settings should seed the terms editor from built-in quote terms');
assert(settings.includes('getSavedQuoteTerms'), 'settings should load saved terms with a built-in fallback');
assert(settings.includes('openSettingsDeepLink'), 'settings should honor quote-builder deep links');
assert(settings.includes("section === 'terms'"), 'settings deep link should scroll to terms section');
assert(settings.includes('terms.unshift'), 'new terms should be inserted at the top of the terms editor');
assert(settings.includes('data-new-term="true"'), 'new terms should be marked for immediate focus');
assert(settings.includes('focusNewTermEditor'), 'adding a term should focus the newly inserted editor');
assert(settings.includes('term-refine-scope'), 'term editor should expose a refinement scope for each term');
assert(settings.includes('refine-term-btn'), 'term editor should include an AI Refine button');
assert(settings.includes('undo-refine-term-btn'), 'term editor should include undo for AI refined terms');
assert(settings.includes('function refineTermText'), 'settings should implement AI term refinement');
assert(settings.includes('function toggleRefinedTerm'), 'settings should allow undo/redo of AI refined terms');
assert(settings.includes('Improve this contractor terms and conditions clause'), 'term refinement should use a terms-specific prompt');

console.log('android full app static test passed');
