const fs = require('fs');
const path = require('path');

function read(file) {
  return fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

const builder = read('quote-builder.html');
const items = read('quote-items.js');
const viewer = read('interactive-quote-viewer.html');
const dashboard = read('dashboard.html');
const invoice = read('invoice-viewer.html');
const supabase = read('supabase-v2.js');
const tradeRulesSchema = read('supabase/ai_trade_rules.sql');
const tradeRuleQuestionMigration = read('supabase/migrations/20260518110000_ai_trade_rule_questions.sql');

assert(builder.includes('createChoiceGroupFromRoomItems'), 'builder should create quote-level choice groups from room items');
assert(builder.includes('applyChoiceGroupSelectionToItem'), 'builder should apply choice group selections to totals');
assert(builder.includes('choiceGroupTemplates'), 'builder should know about reusable choice group templates');
assert(builder.includes('addChoiceTemplateToRoom'), 'builder should attach reusable templates to quote rooms');
assert(builder.includes('openSavedChoiceGroupPicker'), 'builder should use a clickable picker for saved choice groups');
assert(builder.includes('data-saved-choice-group-option'), 'saved choice group picker should render selectable rows');
assert(!builder.includes('Which saved choice group should be added?'), 'saved choice group flow should not ask users to type a number');
assert(builder.includes('autoGroupQuoteItem'), 'builder should auto-wrap added saved items that belong to choice groups');
assert(builder.includes('findAutoChoiceGroupMatches'), 'builder should find reusable groups that match added items');
assert(builder.includes('openAutoChoiceGroupPicker'), 'builder should ask with a picker when an added item matches multiple groups');
assert(builder.includes('turnOffChoiceGrouping'), 'builder should let users turn off grouping for a single line');
assert(builder.includes('Turn Off Grouping'), 'grouped quote rows should expose a Turn Off Grouping action');
assert(builder.includes('autoGroup !== false'), 'builder should treat missing autoGroup as enabled');
assert(builder.includes('openAiVoiceAutoGroupChoiceModal'), 'AI Voice should ask whether to use found saved groups before applying them');
assert(builder.includes('Grouped items found. Use saved groups?'), 'AI Voice grouping prompt should explain that grouped items were found');
assert(builder.includes('openAiVoiceAutoGroupReviewModal'), 'AI Voice should offer a review modal for grouped items');
assert(builder.includes('data-ai-auto-group-include'), 'AI Voice grouping review should let users ungroup selected rows');
assert(builder.includes('openAiVoiceDestinationModal'), 'AI Voice should ask where reviewed items should be added');
assert(builder.includes('aiVoiceDestinationModal'), 'AI Voice destination picker should be a real modal');
assert(builder.includes('confirmAiVoiceDestination'), 'AI Voice destination picker should have an explicit confirm action');
assert(builder.includes('Choose where to add these AI Voice items'), 'AI Voice destination picker should explain the add/create choices');
assert(builder.includes('aiVoiceParsedRoomsList'), 'AI Voice destination picker should list parsed rooms when room breaks are detected');
assert(builder.includes('data-ai-parsed-room-name'), 'AI Voice destination picker should let users rename parsed rooms before adding');
assert(builder.includes("mode: 'parsed'"), 'AI Voice destination picker should support creating the parsed rooms separately');
assert(!builder.includes("var action = 'replace'"), 'AI Voice should not default to replacing quote rooms');
assert(!builder.includes('Choose Cancel to replace everything'), 'AI Voice should not offer overwrite/replace as the cancel action');
assert(builder.includes('ai-voice-review-quantity'), 'AI Voice review should let users correct parsed quantities before adding items');
assert(builder.includes('aiVoiceReviewUnit'), 'AI Voice review should let users correct parsed units before adding items');
assert(builder.includes('_applyAiVoiceReviewQuantityEdit'), 'AI Voice review should apply corrected quantity and unit values before quote creation');
assert(builder.includes('_repairAiTradeRuleReviewItem'), 'AI Voice review should repair stale trade-rule unit/rate from the matched saved item');
assert(builder.includes('_voiceIsGenericFallbackUnit'), 'AI Voice wall paint should treat ls as a generic fallback unit');
assert(builder.includes('_reconcileVoiceExplicitMeasurementQuantity'), 'AI Voice review should trust explicit spoken/calculated LF or sq ft before model guesses');
assert(builder.includes('_voiceReviewRoomHeader'), 'AI Voice review should visually separate parsed rooms');
assert(builder.includes('ai-voice-review-room-header'), 'AI Voice review should render room headers above each parsed room');
assert(builder.includes('seenKeysByRoom'), 'AI Voice duplicate detection should only compare items inside the same parsed room');
assert(builder.includes('ai-voice-height-unit'), 'AI Voice missing height prompt should let users choose feet or inches');
assert(builder.includes('_voiceHeightInputToFeet'), 'AI Voice missing height prompt should convert inches back to feet for wall paint math');
assert(builder.includes('Ceiling height unit'), 'AI Voice missing height prompt should label the feet/inches toggle');
assert(builder.includes('aiVoiceTradeRuleType'), 'AI Trade Rules should expose a rule type selector');
assert(builder.includes('aiVoiceTradeQuestion'), 'AI Trade Rules should collect a clarification question');
assert(builder.includes('aiVoiceQuestionOptionDraftList'), 'AI Trade Rules should show drafted clarification answer options');
assert(builder.includes('addAiVoiceQuestionOptionDraftItem'), 'AI Trade Rules should add answer options before saving a question rule');
assert(builder.includes('editAiVoiceTradeRule'), 'AI Trade Rules should let users edit saved trade rules');
assert(builder.includes('cancelAiVoiceTradeRuleEdit'), 'AI Trade Rules should let users cancel editing and return to new-rule mode');
assert(builder.includes('_aiVoiceEditingTradeRuleId'), 'AI Trade Rules should track which saved rule is being edited');
assert(builder.includes('aiVoiceTradeRuleCancelEdit'), 'AI Trade Rules should expose a Cancel Edit button');
assert(builder.includes('Update Rule'), 'AI Trade Rules edit mode should change the save button to Update Rule');
assert(builder.includes('showAiVoiceClarificationModal'), 'AI Voice should ask unanswered trade-rule questions before review');
assert(builder.includes('aiVoiceClarificationModal'), 'AI Voice should include a clarification modal');
assert(builder.includes('_findClarificationAnswer'), 'AI Voice should auto-select clarification answers from transcript aliases');
assert(builder.includes('_applyAiTradeRuleOptionToResult'), 'AI Voice should turn chosen clarification answers into quote items');
assert(builder.includes('clarification_options'), 'AI Trade Rules should read and write clarification options');
assert(builder.includes('rule_type'), 'AI Trade Rules should preserve direct line item rules and question rules');
assert(builder.includes('openTurnOffChoiceGroupingPicker'), 'turning off a grouped line should ask which item remains');
assert(builder.includes('Which item do you want to remain?'), 'turn off grouping picker should use the requested wording');
assert(builder.includes('toggleRoomAutoGrouping'), 'rooms should expose a grouping toggle');
assert(builder.includes('quoteAutoGroupingDefaultEnabled'), 'room grouping toggle should affect future room defaults');
assert(builder.includes('Disable Grouping'), 'room UI should include Disable Grouping');
assert(builder.includes('openQuoteChoiceGroupOptionPicker'), 'Pick One grouped quote rows should open an option picker from the quote');
assert(builder.includes('changeQuoteChoiceGroupDefault'), 'quote builder should let users change the selected Pick One option');
assert(builder.includes('data-quote-choice-option'), 'quote Pick One picker should render clickable option rows');
assert(builder.includes('Choose Pick One Option'), 'quote Pick One picker should explain that the user is choosing the visible/base option');
assert(builder.includes("var manageItemsRoot = document.getElementById('manageItemsModal')"), 'Manage Items delegated actions should include the top New Item form');
assert(items.includes("document.querySelector('#manageItemsModal .manage-items-add-shell')"), 'Manage Items Hide should collapse the New Item panel shell');
assert(items.includes("document.getElementById('itemListTopAnchor')"), 'Manage Items Hide should collapse the All Items toolbar');
assert(items.includes("calc(80vh - 110px)"), 'Manage Items Hide should expand the item list after the control band is collapsed');
assert(items.includes('details-section-menu'), 'Manage Items Details should open a section picker menu');
assert(items.includes('data-detail-section-toggle'), 'Manage Items Details picker should use checkable section toggles');
assert(items.includes('data-detail-section="description"'), 'Manage Items Details picker should expose Description as its own section');
assert(items.includes('data-detail-section="upgrade"'), 'Manage Items Details picker should expose Upgrade Option as its own section');
assert(items.includes('data-detail-section="labor"'), 'Manage Items Details picker should expose Labor Time as its own section');
assert(items.includes('data-detail-section="supplier-cost"'), 'Manage Items Details picker should expose Supplier / Cost as its own section');
assert(items.includes('data-detail-section="photos"'), 'Manage Items Details picker should expose Photos as its own section');
assert(builder.includes('syncManageDetailsSections'), 'Manage Items delegated click handler should update section visibility from the picker');
const manualAddBlock = builder.slice(builder.indexOf('async function confirmAddLine'), builder.indexOf('function choiceGroupId'));
assert(manualAddBlock.includes('await autoGroupQuoteItem(newItem, rooms[roomIndex])'), 'manual Add Line should route new items through room-aware auto grouping');
const aiApplyBlock = builder.slice(builder.indexOf('async function applyAIQuote'), builder.indexOf('initDone = true'));
assert(aiApplyBlock.includes('prepareAiVoiceAutoGroupingDecision'), 'AI Voice final quote application should prepare a grouping decision before adding rooms');

assert(items.includes('choiceGroupTemplates'), 'manage items should persist reusable choice group templates');
assert(items.includes('openChoiceGroupTemplateModal'), 'manage items should provide a choice group template manager');
assert(items.includes('createChoiceGroupTemplateFlow'), 'choice group manager should launch a new group flow');
assert(items.includes('editChoiceGroupTemplate'), 'choice group manager should edit existing groups');
assert(items.includes('renameChoiceGroupTemplate'), 'choice group manager should rename existing groups');
assert(items.includes('deleteChoiceGroupTemplate'), 'choice group manager should delete existing groups');
assert(items.includes('data-choice-group-template-action'), 'choice group manager should expose row actions');
assert(items.includes('openChoiceGroupHelpModal'), 'choice group manager should include an in-modal help explainer');
assert(items.includes('choiceGroupTemplateHelpBtn'), 'choice group manager header should expose a Help button');
assert(items.includes('Pick One') && items.includes('Pick Multiple') && items.includes('Always use grouping'), 'choice group help should explain choice types and auto grouping');
assert(!builder.includes('quote-items.js?v=1778194800'), 'quote-builder should bump quote-items.js cache after Choice Group manager changes');
assert(items.includes('openChoiceGroupItemPicker'), 'choice group templates should use a searchable saved-item picker');
assert(items.includes('openChoiceGroupDefaultOptionPicker'), 'single choice group templates should use a clickable default-option picker');
assert(items.includes('openChoiceGroupTypePicker'), 'choice group templates should use a clickable type picker');
assert(items.includes('choiceGroupAutoGroupCheckbox'), 'choice group creation should expose auto grouping as a checkbox');
assert(items.includes('autoGroup: picked.autoGroup !== false'), 'new choice group templates should default autoGroup on');
assert(items.includes('autoGroup: picked.autoGroup !== false'), 'edited choice group templates should preserve the autoGroup setting');
assert(items.includes('suggestChoiceGroupTemplates'), 'manage items should suggest but not auto-save possible groups');
assert(items.includes('openChoiceGroupSuggestionPicker'), 'suggested choice groups should render in a picker instead of a text prompt');
assert(items.includes('choiceGroupItemSearch'), 'choice group picker should include a real saved-item search input');
assert(items.includes('data-choice-group-item'), 'choice group picker should render selectable saved items');
assert(items.includes('data-choice-group-default-option'), 'default option picker should render clickable option rows');
assert(items.includes('data-choice-group-type-option'), 'type picker should render clickable type cards');
const templateBlock = items.slice(items.indexOf('async function createChoiceGroupTemplateFlow'), items.indexOf('async function suggestChoiceGroupTemplates'));
assert(templateBlock.includes('openChoiceGroupItemPicker'), 'choice group template flow should open the item picker');
assert(templateBlock.includes('openChoiceGroupDefaultOptionPicker'), 'choice group template flow should open the default option picker');
assert(templateBlock.includes('openChoiceGroupTypePicker'), 'choice group template flow should open the type picker');
assert(!templateBlock.includes('Find Options'), 'choice group template flow should not use the old generic Find Options prompt');
assert(!templateBlock.includes('Which option number is the default/base price?'), 'choice group template flow should not ask for a typed default option number');
assert(!templateBlock.includes('Type "single" for Pick One or "multiple" for Pick Multiple:'), 'choice group template flow should not ask users to type a choice group type');
assert(builder.includes('openChoiceGroupTypePicker'), 'quote-level choice groups should use the clickable type picker when available');
assert(builder.includes('openChoiceGroupDefaultOptionPicker'), 'quote-level choice groups should use the clickable default-option picker when available');
assert(!builder.includes('Which option should be the default/base price?'), 'quote-level choice group default flow should not ask users to type a number');
const suggestBlock = items.slice(items.indexOf('async function suggestChoiceGroupTemplates'), items.indexOf('async function refineDescription'));
assert(!suggestBlock.includes('qdPrompt('), 'suggested choice groups should not ask users to type a number into qdPrompt');

assert(viewer.includes('renderViewerChoiceGroup'), 'client viewer should render choice group cards');
assert(viewer.includes('toggleViewerChoiceOption'), 'client viewer should let clients select choice options');
assert(viewer.includes('renderViewerItemUpgradeGroups'), 'client viewer should render upgrade controls for the selected choice option');
assert(viewer.includes('toggleViewerItemUpgradeOption'), 'client viewer should let clients toggle upgrades on selected choice options');
assert(viewer.includes('applyViewerItemUpgradeGroups(item)'), 'client viewer choice group totals should use upgraded option pricing when selected');
assert(viewer.includes('choice-option-upgrades-wrap'), 'client viewer should render selected choice upgrades in a full-width block below choice cards');
assert(viewer.includes('choice-group-note'), 'client viewer should show visible notes attached to grouped choice items');
assert(viewer.includes('_clientChoiceGroups'), 'client viewer should save selected choice group summaries');
assert(viewer.includes('applyClientChoiceGroupsToRooms'), 'client viewer should apply selected choices on submit or accept');
assert(builder.includes('upgrade: item.upgrade ? cloneSavedItemForQuoteSync(item.upgrade) : null'), 'quote-level choice groups should preserve upgrade data from grouped line items');
assert(items.includes('upgrade: item.upgrade ? JSON.parse(JSON.stringify(item.upgrade)) : null'), 'saved choice group templates should preserve upgrade data from saved items');
assert(read('quote-storage.js').includes('hydrateChoiceGroupOptionsForSave'), 'quote storage should hydrate missing choice option upgrades before sharing/saving');

assert(dashboard.includes('_clientChoiceGroups'), 'dashboard review should show client selected choice groups');
assert(invoice.includes('choiceGroupSelection'), 'invoice should preserve/display accepted choice-group selections');

assert(supabase.includes('sanitizeAiTradeRuleClarificationOptions'), 'Supabase helper should sanitize question rule answer options');
assert(supabase.includes('rule_type'), 'Supabase helper should save the AI trade rule type');
assert(supabase.includes('clarification_question'), 'Supabase helper should save clarification question text');
assert(supabase.includes('clarification_options'), 'Supabase helper should save clarification answer options');

assert(tradeRulesSchema.includes('rule_type text not null default'), 'AI trade rules schema should include rule_type');
assert(tradeRulesSchema.includes('clarification_question text'), 'AI trade rules schema should include clarification_question');
assert(tradeRulesSchema.includes("clarification_options jsonb not null default '[]'::jsonb"), 'AI trade rules schema should include clarification_options');
assert(tradeRuleQuestionMigration.includes('add column if not exists rule_type'), 'migration should add rule_type');
assert(tradeRuleQuestionMigration.includes('add column if not exists clarification_question'), 'migration should add clarification_question');
assert(tradeRuleQuestionMigration.includes('add column if not exists clarification_options'), 'migration should add clarification_options');
