const assert = require('node:assert/strict');
const fs = require('node:fs');
require('../quote-discounts.js');
require('../quote-profit-report.js');
const api = globalThis.QuoteDrProfitReport;
const base = {description:'Door <script>', itemDescription:'Scope & details', quantity:1, rate:2500, total:2500, materialCost:910, _itemUpgradeBaseCaptured:true, _baseRate:2100, _baseMaterialCost:675, upgraded:true, upgradeGroups:[{selectedOptionIds:['mirror'],options:[{id:'mirror',name:'Mirror',upgradeType:'add_on',materialCost:235,rate:400}]}]};
const quote = {total:2825,data:{rooms:[{name:'Bedroom',items:[base,{description:'Not selected',optional:true,optionalSelectedByDefault:false,quantity:1,rate:900,materialCost:500},{_removed:true,quantity:1,rate:100}]}]}};
const before = JSON.stringify(quote);
const result = api.calculate(quote);
assert.equal(result.revenue,2500);
assert.equal(result.materials,910);
assert.equal(JSON.stringify(quote),before,'report must never mutate the quote');
assert(api.html(quote).includes('Door &lt;script&gt;'));
assert(api.html(quote).includes('Scope &amp; details'));
assert.equal(api.material({...base,upgradeGroups:[{selectedOptionIds:['x'],options:[{id:'x',upgradeType:'replacement',materialCost:100,quantityMode:'manual',manualQuantity:3}]}]}),300);
assert.equal(api.material({...base,quantity:2,upgradeGroups:[{selectedOptionIds:['x'],options:[{id:'x',upgradeType:'add_on',materialCost:100,quantityMode:'multiplier',quantityMultiplier:2}]}]}),1750);
assert.equal(api.material({...base,upgradeGroups:[{selectedOptionIds:['x'],options:[{id:'x',upgradeType:'consultation',materialCost:999}]}]}),675);
assert.equal(api.calculate({data:{rooms:[{markup:10,items:[{quantity:1,rate:100,discountType:'percent',discountValue:100,materialCost:10}]}]}}).revenue,0);
assert(api.html({data:{documentType:'change_order'}}).includes('does not estimate'));
const source = fs.readFileSync(require.resolve('../quote-profit-report.js'),'utf8');
assert(!/fetch\(|supabase|localStorage|window\.open|location\./.test(source),'no network, persistence, or client navigation');
console.log('Dashboard private profit report tests passed');
