import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {localClock,isDue,validateSchedule,validateSubscription} from '../supabase/functions/_shared/labor-push-policy.mjs';
const row={enabled:true,reminder_time:'17:30:00',timezone:'America/Toronto',weekends:false};
assert(isDue(row,new Date('2026-09-21T21:30:00Z')));
assert(!isDue(row,new Date('2026-09-21T21:45:00Z')));
assert(!isDue(row,new Date('2026-09-20T21:30:00Z')));
assert(isDue({...row,weekends:true},new Date('2026-09-20T21:30:00Z')));
assert(!isDue({...row,enabled:false},new Date('2026-09-21T21:30:00Z')));
assert(isDue(row,new Date('2026-12-21T22:30:00Z'))); // DST offset changed.
assert.equal(localClock(new Date('2026-09-21T02:00:00Z'),'America/Toronto').date,'2026-09-20');
for(const time of ['07:59','20:00','25:00','junk'])assert.throws(()=>validateSchedule(time,row.timezone));
assert.throws(()=>validateSchedule('17:30',undefined));
assert.throws(()=>validateSchedule('17:30','Made/Up'));
const sub={endpoint:'https://fcm.googleapis.com/fcm/send/example',keys:{p256dh:'a'.repeat(87),auth:'b'.repeat(22)}};
assert.equal(validateSubscription(sub).endpoint,sub.endpoint);
for(const endpoint of ['http://fcm.googleapis.com/a','https://127.0.0.1/a','https://fcm.googleapis.com.evil.test/a','https://user@fcm.googleapis.com/a'])assert.throws(()=>validateSubscription({...sub,endpoint}));
const web=fs.readFileSync('supabase/functions/labor-web-push/index.ts','utf8');
assert(web.indexOf("const claim=await db.from('labor_notification_logs').insert")<web.indexOf('await send(row)'));
assert(web.includes("auth.data.user.id"));assert(web.includes("LABOR_REMINDER_CRON_SECRET"));
assert(web.includes("answered.error||answered.data?.length"));
const native=fs.readFileSync('supabase/functions/labor-notification-dispatch/index.ts','utf8');
assert(native.includes('LABOR_REMINDER_CRON_SECRET'));
const ui=fs.readFileSync('labor-reminders.js','utf8');
assert(ui.indexOf('enable.onclick')<ui.indexOf('Notification.requestPermission()'));
assert(ui.includes('Push service accepted the test'));
const handlers={},shown=[],opened=[];
const context={self:{addEventListener:(name,fn)=>handlers[name]=fn,registration:{showNotification:(...args)=>{shown.push(args);return Promise.resolve();}},clients:{openWindow:url=>{opened.push(url);return Promise.resolve();}}}};
vm.runInNewContext(fs.readFileSync('sw.js','utf8'),context);
await handlers.push({data:{json:()=>({type:'qdr-labor',title:'Private client info',url:'https://evil.test'})},waitUntil:p=>p});
assert.equal(shown.length,1);assert(!shown[0][0].includes('Private'));
await handlers.notificationclick({notification:{data:{type:'qdr-labor',url:'https://evil.test'},close(){}},waitUntil:p=>p});
assert.equal(opened[0],'/labor-tracker.html#laborWorklog');
handlers.push({data:{json:()=>{throw Error('bad JSON');}}});
assert.equal(shown.length,1);
// Parse TypeScript and execute the real HTTP handler with a minimal denied-auth mock.
let handle;
const code=stripTypeScriptTypes(web.replace(/^import .*;\r?\n/gm,''));
vm.runInNewContext(code,{Deno:{env:{get:()=>undefined},serve:fn=>handle=fn},Response,JSON,Date,Number,Error,createClient:()=>({auth:{getUser:async()=>({error:true,data:{user:null}})}})});
assert.equal((await handle(new Request('https://example.test',{method:'POST',body:JSON.stringify({action:'dispatch'})}))).status,401);
assert.equal((await handle(new Request('https://example.test',{method:'POST',body:JSON.stringify({action:'test'})}))).status,401);
assert.equal((await handle(new Request('https://example.test'))).status,405);
console.log('Labour push policy and static safety checks passed (not runtime delivery proof).');
