const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const source = fs.readFileSync('quote-builder.html', 'utf8');
const nodes = {};
const makeNode = () => ({style:{}, appendChild(){}, replaceChildren(){}, setAttribute(){}, click(){}});
const context = vm.createContext({ document: {createElement: makeNode, getElementById(id) { return nodes[id] ||= makeNode(); } } });
vm.runInContext(source.slice(source.indexOf('let linePhotoDraft ='), source.indexOf('function addLine(roomId)')), context);
vm.runInContext(`
const original = {photo:'old', photos:['old'], photoFull:{path:'old'}};
resetLinePhotoDraft(original);
removeLinePhoto(0);
if (original.photo !== 'old') throw Error('cancel must not mutate item');
resetLinePhotoDraft(original);
const unchanged = JSON.stringify(original);
applyLinePhotoDraft(original);
if(JSON.stringify(original)!==unchanged) throw Error('untouched draft');
linePhotoDraft.photos=['new']; linePhotoDraft.full=[null]; linePhotoDraft.changed=true;
applyLinePhotoDraft(original);
if(original.photo!=='new'||original.photos[0]!=='new'||original.photoFull!==null||!original.quotePhotoOverride) throw Error('replace');
removeLinePhoto(0); applyLinePhotoDraft(original);
if(original.photo!==''||original.photos.length) throw Error('remove');
const restored=JSON.parse(JSON.stringify(original));
if(!restored.quotePhotoOverride) throw Error('serialization');
resetLinePhotoDraft({photo:'other'});
if(linePhotoDraft.changed||linePhotoDraft.photos[0]!=='other') throw Error('draft leak');
resetLinePhotoDraft({photos:['one','two','three'], photosFull:['full1','full2','full3']});
removeLinePhoto(1);
const multiple={_basePhoto:'old'};
applyLinePhotoDraft(multiple);
if(multiple.photos.join()!=='one,three'||multiple.photosFull.join()!=='full1,full3'||multiple._basePhotos.join()!=='one,three') throw Error('remove must preserve other photos and metadata');
resetLinePhotoDraft(JSON.parse(JSON.stringify(multiple)));
if(linePhotoDraft.photos.join()!=='one,three') throw Error('reload lost photos');
`,context);
assert(source.includes('if (item.quotePhotoOverride) return item;'));
assert(source.includes('if (item.quotePhotoOverride) return false;'));
for (const script of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) {
  if(script[1].trim() && !script[0].includes('application/ld+json')) new vm.Script(script[1]);
}
console.log('Line photo draft and builder syntax tests passed');
