const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('quote-builder.html', 'utf8');
const fn = source.slice(source.indexOf('function bindCategoryPickerChoices('), source.indexOf('function refreshOpenCategoryPicker('));
let handler, saves = [], alerts = [], match = 'fa-hammer';
const ctx = {detectQuoteCategoryIcon: () => match, selectCatIcon: (...args) => saves.push(args), qdAlert: msg => alerts.push(msg)};
vm.createContext(ctx); vm.runInContext(fn, ctx);
const picker = {dataset: {}, addEventListener: (_, cb) => { assert.equal(handler, undefined); handler = cb; }};
ctx.bindCategoryPickerChoices(picker, 'Carpentry');
ctx.bindCategoryPickerChoices(picker, 'Carpentry');
const event = {target: {closest: selector => selector === '[data-cat-auto-detect]' ? {} : null}, preventDefault() {}, stopPropagation() {}};
handler(event);
assert.deepEqual(saves, [['Carpentry', 'fa-hammer']]);
match = null; handler(event);
assert.equal(saves.length, 1);
assert.equal(alerts.length, 1);
assert(source.includes('data-cat-auto-detect><i'));
console.log('Manage category auto icon: match, no match and single listener passed');
