const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('dashboard.html','utf8');
const code = source.slice(source.indexOf('        function showNotificationActivity('),source.indexOf('        async function toggleClientActivityRead('));
let hidden, shown, onClose, args, hides=0, shows=0, focuses=0;
const event = {id:'alert',document_id:'invoice-123',client_name:'Sample',quote_number:'I-1',document_title:'Invoice',read_at:null};
const modalEl = {addEventListener(name,fn){if(name==='hidden.bs.modal')hidden=fn;else shown=fn;}};
const modal = {hide(){hides++;},show(){shows++;}};
const ui = {activity(...values){args=values;onClose=values[2];}};
const scope = {clientActivityEvents:[event],document:{getElementById:()=>modalEl},bootstrap:{Modal:{getOrCreateInstance:()=>modal}},window:{QuoteDrDashboardUI:ui},QuoteDrDashboardUI:ui};
vm.createContext(scope); vm.runInContext(code,scope);
const button = {getAttribute:()=>event.id,isConnected:true,focus(){focuses++;}};
scope.showNotificationActivity(button);
assert.equal(hides,1); assert.equal(args,undefined,'must wait for Bootstrap focus trap to close');
hidden(); assert.equal(args[0],'invoice-123'); assert.match(args[1],/I-1/);
onClose(); shown(); assert.equal(shows,1); assert.equal(focuses,1); assert.equal(event.read_at,null);
event.document_id=null; scope.showNotificationActivity(button); assert.equal(hides,1);
assert(source.includes('Show Activity</button>'));
console.log('Notification Activity: correct document, focus handoff, return, unchanged unread, unlinked guard passed');
