const assert = require('node:assert');
const fs = require('node:fs');

const source = fs.readFileSync('quote-builder.html', 'utf8');

assert(source.includes('QuoteDr Tutorial'), 'builder guide should be presented as the QuoteDr tutorial');
assert(source.includes("first_quote"), 'tutorial should include a first quote track');
assert(source.includes("advanced_tools"), 'tutorial should include an advanced tools track');
assert(source.includes("ald_onboarding_completed_steps"), 'tutorial should persist completed onboarding steps');
assert(source.includes('id="builderGuideRestartBtn"'), 'tutorial should expose a contextual restart button');
assert(source.includes('restartCurrentBuilderGuideTrack'), 'tutorial should restart the current tutorial track');
assert(source.includes("stepKey.indexOf(_builderGuideTrack + ':') !== 0"), 'restart should only clear completed state for the current track');
assert(source.includes("delete map[key]"), 'restart should clear saved substeps for the current track');
assert(source.includes('getBuilderGuideTrackLabel'), 'restart button should name the current tutorial track');
assert(source.includes('id="builderGuideRestartStepBtn"'), 'tutorial should expose a per-step restart button');
assert(source.includes('restartCurrentBuilderGuideStep'), 'tutorial should restart the selected tutorial step');
assert(source.includes('resetBuilderGuideStepState'), 'tutorial should clear one step without clearing the whole track');
assert(source.includes('return stepKey !== key;'), 'step restart should remove only the selected completed step');
assert(source.includes("title: 'Restart this tutorial?'"), 'step restart should confirm before clearing step progress');
assert(source.includes("ald_onboarding_restarted_tracks"), 'track restart should remember that auto-complete is suppressed');
assert(source.includes("ald_onboarding_restarted_steps"), 'step restart should remember that auto-complete is suppressed for one step');
assert(source.includes('isBuilderGuideTrackRestarted(_builderGuideTrack)'), 'tutorial status should know when the current track was restarted');
assert(source.includes('isBuilderGuideStepRestarted(step)'), 'tutorial status should know when the current step was restarted');
assert(source.includes('if (!suppressAutoComplete)'), 'restarted tutorials should not auto-complete from existing quote data');
assert(source.includes('setBuilderGuideTrackRestarted(_builderGuideTrack, true)'), 'full track restart should clear the visual step status completely');
assert(source.includes('id="builderGuideStopBtn"'), 'tutorial should expose a sticky stop button near the chatbot');
assert(source.includes('function stopBuilderGuide()'), 'sticky stop button should be able to stop the tutorial');
assert(source.includes("target: '#builderGuideStopBtn'"), 'first tutorial step should point at the sticky stop button');
assert(source.includes('You can stop the tutorial anytime'), 'first tutorial step should explain the stop button');
assert(source.includes("stopBtn.style.display = hidden ? 'none' : 'inline-flex'"), 'stop button should only show while the guide is active');
assert(source.includes('#builderGuideStopBtn.builder-guide-spotlight'), 'stop button should stay fixed when the tutorial spotlight highlights it');
assert(source.includes("Build your first quote"), 'tutorial should start with first-quote onboarding copy');
assert(source.indexOf("id: 'stop_control'") < source.indexOf("id: 'welcome'"), 'stop tutorial step should be shown before the first quote walkthrough');
assert(source.includes("target: '#builderGuideActionBtn'"), 'welcome step should spotlight the Start button instead of the client info field');
assert(source.includes('Click Start to begin the client info walkthrough'), 'welcome coachmark should explain how to move into client info');
assert(source.includes("AI Voice can turn spoken scope into accurate rooms and line items in seconds"), 'tutorial should position AI Voice as a strong time-saving workflow');
assert(source.includes("AI Voice saves serious time and learns from your corrections"), 'tutorial coachmark should emphasize AI Voice speed and learning');
assert(source.includes("target: '#voiceMicBtn'"), 'AI Voice tutorial should continue inside the modal and target the mic');
assert(source.includes('Try it out: hit the microphone button now'), 'AI Voice tutorial should clearly prompt the user to try the mic');
assert(source.includes("target: '#voiceTranscript'"), 'AI Voice tutorial should explain the transcript area');
assert(source.includes('id="voiceNextRoomBtn"'), 'AI Voice tutorial should have a stable target for the Next Room control');
assert(source.includes("target: '#voiceNextRoomBtn'"), 'AI Voice tutorial should explain room breaks');
assert(source.includes('id="aiVoiceMemoryBtn"'), 'AI Voice tutorial should have a stable target for AI Memory');
assert(source.includes('id="aiVoiceTradeRulesBtn"'), 'AI Voice tutorial should have a stable target for AI Trade Rules');
assert(source.includes('id="aiVoiceTemplatesBtn"'), 'AI Voice tutorial should have a stable target for Voice Templates');
assert(source.includes('syncBuilderGuideWithAiVoiceModal'), 'tutorial should advance when the AI Quote Builder modal opens');
assert(source.includes('syncBuilderGuideWithAiVoiceReview'), 'tutorial should continue when the AI Voice review page opens');
assert(source.includes("target: '#aiVoiceReviewList'"), 'AI Voice tutorial should explain the verification/review page');
assert(source.includes("voiceQuoteModal.addEventListener('shown.bs.modal'"), 'AI Voice modal should notify the tutorial when opened');
assert(source.includes("aiVoiceReviewModal.addEventListener('shown.bs.modal'"), 'AI Voice review modal should notify the tutorial when opened');
assert(source.includes("if (typeof syncBuilderGuideWithAiVoiceModal === 'function')"), 'startVoiceQuote should explicitly advance the tutorial when opening AI Voice');
assert(source.includes("if (typeof syncBuilderGuideWithAiVoiceReview === 'function')"), 'showAiVoiceReview should explicitly advance the tutorial when review opens');
assert(source.includes("coachDoneBtn.style.display = (step.manualComplete || activeStep.manualComplete)"), 'coachmark should allow explicit completion on final guided substeps');
assert(source.includes("Satellite Measure is best outdoors"), 'tutorial should explain measurement tool fit');
assert(source.includes("Create linked changes without editing the original quote"), 'tutorial should include change order onboarding');
assert(source.includes("Mark Done"), 'tutorial should allow optional steps to be completed manually');
assert(source.includes("setBuilderGuideTrack('advanced_tools')"), 'tutorial should expose the power tools track');
assert(source.includes('onclick="toggleBuilderGuide()"'), 'guide visibility should use one persistent toggle button');
assert(source.includes("showBtn.innerHTML = hidden"), 'guide toggle label should switch between show and hide states');
assert(!source.includes('onclick="toggleBuilderGuide(false)"'), 'guide card should not include a second hide button');
assert(source.includes('builder-guide-spotlight'), 'tutorial should spotlight the next target element');
assert(source.includes('builder-guide-coachmark'), 'tutorial should show an on-page coachmark beside the next target');
assert(source.includes('builder-guide-backdrop'), 'tutorial should dim the page around the active target');
assert(source.includes('applyBuilderGuideSpotlight'), 'tutorial should update spotlight/callout state as steps change');
assert(source.includes('clearBuilderGuideSpotlight'), 'tutorial should clean up spotlight state when hidden');
assert(source.includes("target: '.btn-add-room'"), 'room step should target the Add Room button');
assert(source.includes("target: '#clientName'"), 'client step should target the client name field');
assert(source.includes('scrollIntoView'), 'tutorial should scroll the next target into view');
assert(source.includes('id="builderGuideCoachDoneBtn"'), 'coachmark should include an inline completion button');
assert(source.includes('id="builderGuideCoachNextBtn"'), 'coachmark should include an inline next button for field-by-field walkthroughs');
assert(source.includes('manualComplete: true'), 'client info should support manual tutorial completion');
assert(source.includes('substeps: ['), 'client info should support multiple guided substeps');
assert(source.includes("target: '#projectAddress'"), 'client info walkthrough should target project address after client name');
assert(source.includes("target: '#clientPhone'"), 'client info walkthrough should target phone number');
assert(source.includes("target: '#clientEmail'"), 'client info walkthrough should target email address');
assert(source.includes('function moveBuilderGuideSubstep(delta)'), 'tutorial should support moving between coachmark substeps');
assert(source.includes('var _builderGuideManualStepIndex = null'), 'tutorial should track when the user manually selected a step');
assert(source.includes('setBuilderGuideStep(_builderGuideIndex + delta, true)'), 'back/next tutorial buttons should use manual step navigation');
assert(source.includes('_builderGuideManualStepIndex !== _builderGuideIndex'), 'auto-advance should not override manually selected completed steps');
assert(source.includes('isBuilderGuideLastSubstep(step)'), 'tutorial should know when to show only the completion button');
assert(source.includes("complete: function() { return isBuilderGuideStepCompleted('first_quote:client'); }"), 'client info should not auto-complete just because fields contain text');
assert(!source.includes("isBuilderGuideStepCompleted('first_quote:welcome') || isBuilderGuideClientInfoReady()"), 'welcome step should not skip ahead from prefilled client info');
assert(source.indexOf("id: 'saved_item_setup'") > source.indexOf("id: 'room'"), 'saved item setup should happen after adding a room');
assert(source.indexOf("id: 'saved_item_setup'") < source.indexOf("id: 'items'"), 'saved item setup should happen before adding quote line items');
assert(source.includes("target: '.btn-manage'"), 'saved item setup should first target Manage Items');
assert(source.includes('id="lineItemQuickSearchTip"'), 'add line item modal should include a quick-search saved-item tip');
assert(source.includes('Start typing a saved item name'), 'add line item modal should explain saved item search autofill');
assert(source.includes("target: '#itemQuickSearch'"), 'line item tutorial should point at the quick search field after opening the modal');
assert(source.includes('Saved items save tons of time'), 'line item tutorial should explain why saved items matter');
assert(source.includes("target: '#newItemName'"), 'saved item setup should guide the new saved item name');
assert(source.includes("target: '#newItemMaterialCost'"), 'saved item setup should include material cost guidance');
assert(source.includes('QuickBooks Products & Services'), 'builder tutorial should mention QuickBooks products/services sync');
assert(source.includes('Importer tool in Settings'), 'builder tutorial should mention the settings importer fallback');
assert(source.includes("closeModalOnComplete: 'manageItemsModal'"), 'saved item setup should close Manage Items before advancing');
assert(source.includes('function closeBuilderGuideModalBeforeAdvance(step, onClosed)'), 'tutorial should support closing modal steps before advancing');
assert(source.includes("modalEl.addEventListener('hidden.bs.modal'"), 'tutorial should wait for Bootstrap modal close before advancing');

console.log('onboarding guide static test passed');
