import assert from 'node:assert/strict';
import fs from 'node:fs';
import {sanitizeClientDocumentRow} from '../supabase/functions/_shared/client-document-policy.mjs';
const source={data:{rooms:[],portal_job_folders:[{id:'folder-1',name:'Renovation',documentIds:['quote-1'],designIds:['design-1'],notes:'PRIVATE',unexpected:'PRIVATE'}]}};
const before=JSON.stringify(source);
const result=sanitizeClientDocumentRow(source);
assert.equal(result.data.portal_job_folders[0].name,'Renovation');
assert.deepEqual(result.data.portal_job_folders[0].designIds,['design-1']);
assert(!JSON.stringify(result).includes('PRIVATE'));
assert.equal(JSON.stringify(source),before);
const html=fs.readFileSync('client-portal.html','utf8');
assert(html.includes("Object.assign({}, fresh.data || {})"),'save preserves full stored quote, not projected data');
assert(html.includes('fresh.updated_at!==row.updated_at'),'concurrent changes blocked');
assert(html.includes('saved.data?.portal_job_folders'),'readback required');
assert(html.includes('Select designs &amp; renderings'));
const js=fs.readFileSync('portal-designs.js','utf8');
assert(js.includes('row.visible && ids.includes(row.id)'));
assert(js.includes("button('Open design',()=>openDesign(row)"),'folder uses existing ordered-review opener');
console.log('PASS folder projection, private-note exclusion, design membership and safe save checks');
