const fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync('quote-builder.html','utf8');
const code=source.slice(source.indexOf('        function renderRecommendedPortalGroups('),source.indexOf('        function renderInvoicePortalAssignmentList('));
const render=new Function('invoiceMatchesPortal',code+';return renderRecommendedPortalGroups;')((p,d)=>p.client===d.client);
const portals=[{id:'a',name:'Alpha',client:'other'},{id:'z',name:'Zed',client:'match'},{id:'b',name:'Beta',client:'other'},{id:'t',name:'Thomas',client:'match'}];
const before=JSON.stringify(portals),card=p=>'<article>'+p.id+'</article>';
let html=render(portals,{client:'match'},card);
assert(html.indexOf('Recommended portals')<html.indexOf('<article>t'));
assert(html.indexOf('<article>t')<html.indexOf('<article>z'));
assert(html.indexOf('<article>z')<html.indexOf('Other portals'));
assert(html.indexOf('Other portals')<html.indexOf('<article>a'));
assert(html.indexOf('<article>a')<html.indexOf('<article>b'));
for(const p of portals)assert.equal(html.split(card(p)).length-1,1);
assert.equal(JSON.stringify(portals),before);
html=render(portals,{client:'missing'},card);assert(!html.includes('<section'));assert(html.indexOf('<article>a')<html.indexOf('<article>t'));
assert(!render(portals.filter(p=>p.client==='match'),{client:'match'},card).includes('Other portals'));
assert.equal(render([],{client:'match'},card),'');
assert.match(source,/renderRecommendedPortalGroups\(portals, invoiceData,/);
assert.match(source,/renderRecommendedPortalGroups\(portals, quoteData,/);
console.log('PASS recommended first, alphabetical within groups, no duplicated cards, unchanged registry, no/all matches, both pickers');
