import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.env.QD_PGLITE_MODULE).href);
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);`);
await db.exec(await fs.readFile('supabase/migrations/20260907021911_portal_design_library.sql','utf8'));
const permissions=await db.query(`select has_table_privilege('anon','public.portal_designs','select') a,has_table_privilege('authenticated','public.portal_designs','select') u,has_table_privilege('service_role','public.portal_designs','select') s`);
assert.deepEqual(permissions.rows[0],{a:false,u:false,s:true});
const rls=await db.query(`select count(*)::int as n from pg_class where relname in ('portal_designs','portal_design_libraries','portal_design_pin_attempts') and relrowsecurity`);assert.equal(rls.rows[0].n,3);
await db.exec(`set role service_role`);
for(let i=1;i<=11;i++)assert.equal((await db.query(`select public.portal_design_pin_attempt('fixture') allowed`)).rows[0].allowed,i<=10);
await db.exec(`update public.portal_design_pin_attempts set window_start=now()-interval '16 minutes' where scope='fixture'`);
assert.equal((await db.query(`select public.portal_design_pin_attempt('fixture') allowed`)).rows[0].allowed,true);
await db.exec('reset role; set role anon');
await assert.rejects(db.query('select * from public.portal_designs'),/permission denied/);
await assert.rejects(db.query("select public.portal_design_pin_attempt('bypass')"),/permission denied/);
await db.exec('reset role');
assert.equal((await db.query("select public from storage.buckets where id='portal-designs'")).rows[0].public,false);
await db.close();console.log('PASS: migration executes, RLS enabled, public roles denied, service-role access, PIN rate limiting and reset, private bucket');
