import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.env.QD_PGLITE_MODULE).href);
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);`);
await db.exec(await fs.readFile('supabase/migrations/20260907021911_portal_design_library.sql','utf8'));
await db.exec(await fs.readFile('supabase/migrations/20260922025938_portal_render_upload_allowance.sql','utf8'));
await db.exec(`insert into auth.users values ('11111111-1111-4111-8111-111111111111');
insert into public.portal_design_libraries(id,user_id,portal_id,share_token) values('22222222-2222-4222-8222-222222222222','11111111-1111-4111-8111-111111111111','fixture','fixture');`);
const add=(id,path)=>db.query(`insert into public.portal_designs(id,library_id,title,kind,storage_path,size_bytes) values($1,'22222222-2222-4222-8222-222222222222','Render','interactive',$2,30000000)`,[id,path]);
await add('33333333-3333-4333-8333-333333333333','first');
await db.exec(`update public.portal_designs set title='Renamed',visible=false where storage_path='first'`);
await db.exec(`begin; update public.portal_designs set storage_path='failed-replacement'; rollback;`);
assert.equal((await db.query('select uploads from public.portal_render_upload_months')).rows[0].uploads,1);
await db.exec(`update public.portal_designs set storage_path='second'`);
await add('44444444-4444-4444-8444-444444444444','third');
await assert.rejects(add('55555555-5555-4555-8555-555555555555','fourth'),/render_upload_quota_exceeded/);
await db.exec('delete from public.portal_designs');
await assert.rejects(add('55555555-5555-4555-8555-555555555555','after-delete'),/render_upload_quota_exceeded/);
await db.exec(`update public.portal_render_upload_months set month_start=(month_start-interval '1 month')::date`);
await add('55555555-5555-4555-8555-555555555555','next-month');
await assert.rejects(db.query('update public.portal_designs set size_bytes=30000001'),/check constraint/);
assert.equal((await db.query("select file_size_limit from storage.buckets where id='portal-designs'")).rows[0].file_size_limit,30000000);
const permissions=await db.query(`select has_table_privilege('anon','public.portal_designs','select') a,has_table_privilege('authenticated','public.portal_designs','select') u,has_table_privilege('service_role','public.portal_designs','select') s`);
assert.deepEqual(permissions.rows[0],{a:false,u:false,s:true});
const rls=await db.query(`select count(*)::int as n from pg_class where relname in ('portal_designs','portal_design_libraries','portal_design_pin_attempts') and relrowsecurity`);assert.equal(rls.rows[0].n,3);
await db.exec(`set role service_role`);
for(let i=1;i<=11;i++)assert.equal((await db.query(`select public.portal_design_pin_attempt('fixture') allowed`)).rows[0].allowed,i<=10);
await db.exec(`update public.portal_design_pin_attempts set window_start=now()-interval '16 minutes' where scope='fixture'`);
assert.equal((await db.query(`select public.portal_design_pin_attempt('fixture') allowed`)).rows[0].allowed,true);
await db.exec('reset role; set role anon');
await assert.rejects(db.query('select * from public.portal_designs'),/permission denied/);
await assert.rejects(db.query('select * from public.portal_render_upload_months'),/permission denied/);
await assert.rejects(db.query("select public.portal_design_pin_attempt('bypass')"),/permission denied/);
await db.exec('reset role');
assert.equal((await db.query("select public from storage.buckets where id='portal-designs'")).rows[0].public,false);
await db.close();console.log('PASS: migration executes, RLS enabled, public roles denied, service-role access, PIN rate limiting and reset, private bucket');
