const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('quote-style.js','utf8');
const extract=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)));
const old={descriptionPreviewLength:600,alwaysShowFullDescriptions:true};
const ctx={window:{_loadedQuoteData:{style:{...old}},_currentQuoteData:{style:{...old}}},_quoteStyle:{...old},JSON,alert:()=>{},quoteStudioClone:v=>JSON.parse(JSON.stringify(v)),readQuoteStyleFromControls:()=>({descriptionPreviewLength:120,alwaysShowFullDescriptions:false}),collectQuoteData:()=>({id:'synthetic',style:{...old}}),markUnsaved:()=>ctx.dirty=true,localStorage:{setItem:(k,v)=>ctx.saved=JSON.parse(v)}};
ctx.syncQuoteStyleGlobal=()=>ctx.window._quoteStyle=ctx._quoteStyle;
vm.createContext(ctx);
vm.runInContext(extract('        function applyQuoteStyleToCurrentDraft()', '        async function confirmGenerateQuote()'),ctx);
assert.equal(ctx.applyQuoteStyleToCurrentDraft(),true);
assert.equal(ctx.saved.style.descriptionPreviewLength,120);
assert.equal(ctx.window._loadedQuoteData.style.descriptionPreviewLength,120);
assert.equal(ctx.window._currentQuoteData.style.alwaysShowFullDescriptions,false);
assert.equal(ctx.dirty,true);
ctx.localStorage.setItem=()=>{throw new Error('quota');};ctx.dirty=false;
assert.equal(ctx.applyQuoteStyleToCurrentDraft(),false);assert.equal(ctx.dirty,false);
const done=extract('            if (window._quoteStyleSettingsOnly)', '            var generateBtn');
assert(done.includes('applyQuoteStyleToCurrentDraft()'));
assert(!done.includes('saveQuoteStyleDefaults'));
const cloud=extract('        async function saveQuoteStyleDefaultsToCloud(', '        async function loadQuoteStyleDefaults(');
assert(cloud.includes("!== 'cloud_saved'"));assert(cloud.includes('throw e'));
console.log('Settings: current draft/session snapshots, dirty state, storage failure, separate defaults and confirmed-cloud gate passed.');
