const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const records = new Map();
const storage = {get length(){return records.size},key:i=>[...records.keys()][i],getItem:k=>records.get(k),setItem:(k,v)=>records.set(k,v),removeItem:k=>records.delete(k)};
const context = vm.createContext({URL,console,sessionStorage:storage,crypto:{randomUUID:()=> 'test'},QuoteDrDiscounts:{chargedTotal:i=>i.total},Date});
vm.runInContext(fs.readFileSync('quote-profit-report.js','utf8'),context);
vm.runInContext(fs.readFileSync('quote-pdf-export.js','utf8'),context);
const api = context.QuoteDrPdfExport;
const data = {quoteNumber:'Q1',quoteTitle:'<img onerror=evil()>',grandTotal:100,rooms:[{name:'Room',items:[{description:'Test',quantity:1,total:100,materialCost:20}]}]};
const before = JSON.stringify(data);
const url = () => new URL('https://example.test/interactive-quote-viewer?id=one&admin_preview=1&print=1');
let target = url(); api.stage(data,target,true);
let payload = api.consume(target);
assert(payload.html.includes('Before labour &amp; overhead'));
assert(payload.html.includes('$80.00'));
assert(!payload.html.includes('<img'));
assert.equal(records.size,0,'one shot');
assert.throws(()=>api.consume(target),/unavailable/);
target = url(); api.stage(data,target,false);
assert(!api.consume(target).html.includes('Profit report'));
target = url(); api.stage(data,target,true); target.searchParams.set('id','another');
assert.throws(()=>api.consume(target),/unavailable/);
target = url(); api.stage(data,target,true); target.searchParams.delete('admin_preview');
assert.throws(()=>api.consume(target),/unavailable/);
target = url(); api.stage(data,target,true);
const key=target.searchParams.get('internal_export');
payload=JSON.parse(records.get(key)); payload.createdAt-=301000; records.set(key,JSON.stringify(payload));
assert.throws(()=>api.consume(target),/expired/);
assert.equal(JSON.stringify(data),before,'export must not mutate quote');
assert.equal(api.consume(url()),null,'normal client preview has no appendix');
console.log('Internal PDF privacy, totals, escaping, expiry, document binding and one-shot tests passed');
