import assert from 'node:assert/strict';
import {installStorageBudget,usageMessage} from '../storage-budget-client.mjs';
const calls=[];
const usage={retainedBytes:1e9,reservedBytes:0,retainedLimit:10e9,monthlyBytes:1.9e9,monthlyLimit:2e9};
const client={functions:{invoke:async(name,args)=>{calls.push([name,args.body]);return {data:{data:{path:'owner/file'},usage}};}},storage:{from:()=>({upload:()=>42,remove:()=>43})}};
const budget=installStorageBudget(client,()=> 'account');
assert.equal(installStorageBudget(client),budget);
await client.storage.from('room-photos').upload('owner/file',new Blob(['photo']));
assert(calls[0][1] instanceof FormData);
assert.equal(JSON.parse(calls[0][1].get('metadata')).accountId,'account');
assert.equal(client.storage.from('unmanaged').upload(),42);
await client.storage.from('portal-job-assets').remove(['owner/file']);
assert.equal(calls[1][1].action,'remove');
await budget.usage();assert.equal(calls[2][1].action,'usage');
assert.match(usageMessage(usage),/Storage warning/);
assert.match(usageMessage({...usage,warningOnly:true,monthlyBytes:3e9}),/threshold exceeded/);
assert.match(usageMessage({...usage,warningOnly:true}),/do not block uploads/);
client.functions.invoke=async()=>({error:{message:'generic',context:{json:async()=>({error:'Quota reached'})}}});
assert.equal((await budget.usage()).error.message,'Quota reached');
console.log('PASS storage adapter multipart upload, account scope, removal, usage, errors and warnings');
