import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.env.QD_PGLITE_MODULE).href);
const db=new PGlite();
const owner='11111111-1111-4111-8111-111111111111';
const second='22222222-2222-4222-8222-222222222222';
const exempt='25bbd251-205a-425d-9f9c-5509cc3c6d1c';
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create schema storage; create table storage.objects(bucket_id text,name text,metadata jsonb,primary key(bucket_id,name));
alter table storage.objects enable row level security;
grant usage on schema storage to authenticated,anon,service_role;
grant all on storage.objects to authenticated,anon,service_role;
create policy old_allow on storage.objects for all to authenticated using(true) with check(true);
create table public.accounts(owner_user_id uuid); create table public.portal_designs(id uuid);
insert into auth.users values('${owner}'),('${second}'),('${exempt}'); insert into accounts values('${owner}'),('${exempt}');
insert into storage.objects values('room-photos','${owner}/old','{"size":100}');`);
await db.exec(await fs.readFile('supabase/migrations/20260924163345_shared_storage_budget.sql','utf8'));
await db.exec(await fs.readFile('supabase/migrations/20260925151506_shared_storage_policy_cutover.sql','utf8'));
const status=async(id=owner)=>(await db.query('select public.qdr_storage_status($1) s',[id])).rows[0].s;
const reserve=async(path,size=40,id=owner,digest='same')=>(await db.query('select public.qdr_storage_reserve($1,$2,$3,$4,$5) s',[id,'room-photos',id+'/'+path,size,digest])).rows[0].s;
assert.equal((await status()).retainedLimit,21474836480);
assert.equal((await status(second)).retainedLimit,10000000000);
assert.equal((await status()).warningOnly,false);
assert.equal((await status(exempt)).warningOnly,true,'Only verified owner is seeded warning-only');
await db.exec(`update public.qdr_storage_accounts set retained_limit=10,monthly_limit=10 where owner_id='${exempt}'`);
await reserve('above-both-limits',40,exempt);
assert.equal((await status(exempt)).monthlyBytes,40,'Exempt owner still metered above warning threshold');
await db.exec(`update public.qdr_storage_accounts set retained_limit=1000,monthly_limit=80 where owner_id='${owner}'; set role service_role;`);
await reserve('a');await reserve('a');
assert.equal((await status()).monthlyBytes,40,'Retry counted once');
await reserve('b');await assert.rejects(reserve('c'),/storage_monthly_limit/);
await db.exec(`insert into storage.objects values('room-photos','${owner}/a','{"size":20}');`);
assert.equal((await status()).monthlyBytes,60,'Actual signed-upload size replaces reserved size');
await db.exec(`delete from storage.objects where name='${owner}/a'`);
assert.equal((await status()).monthlyBytes,60,'Deletion does not refund monthly allowance');
assert.equal((await status()).reservedBytes,80,'Unexpired capabilities retain headroom after deletion');
await assert.rejects(reserve('a'),/storage_upload_expired/);
await db.exec(`update public.qdr_storage_uploads set expires_at=now()-interval '1 second' where path='${owner}/b'`);
assert.equal((await status()).monthlyBytes,20,'Expired unfulfilled reservation releases bytes');
await reserve('c',40);
await db.exec(`update public.qdr_storage_uploads set created_at=now()-interval '40 days' where path='${owner}/c'`);
assert.equal((await status()).monthlyBytes,60,'Pending reservations survive month rollover');
await db.exec(`update public.qdr_storage_accounts set retained_limit=150 where owner_id='${owner}'`);
await assert.rejects(reserve('d',20),/storage_retained_limit/);
await db.exec('reset role; set role authenticated');
await assert.rejects(status(),/permission denied/);
await assert.rejects(db.exec(`update public.qdr_storage_accounts set warning_only=true where owner_id='${owner}'`),/permission denied/);
await assert.rejects(db.exec(`insert into storage.objects values('room-photos','bypass','{"size":1}')`),/row-level security/);
await db.exec('reset role');
await db.close();console.log('PASS shared storage SQL: allowances, retries, monthly rollover, deletion, expiry, retained budget, permissions and direct-upload blocking');
