-- Account-owner birthday preferences and annual rewards.
-- Birth years are deliberately not collected.

create table if not exists public.birthday_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  birth_month smallint not null check (birth_month between 1 and 12),
  birth_day smallint not null check (
    birth_day between 1 and case
      when birth_month in (1, 3, 5, 7, 8, 10, 12) then 31
      when birth_month in (4, 6, 9, 11) then 30
      else 29
    end
  ),
  timezone text not null default 'UTC' check (char_length(timezone) between 1 and 80),
  birthday_set_at timestamptz not null default now(),
  birthday_changed_at timestamptz,
  self_service_change_available_at timestamptz not null default (now() + interval '365 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.birthday_reward_claims (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_type text not null check (reward_type in ('standard_pro_week', 'pro_renewal_credit')),
  eligible_plan text not null check (eligible_plan in ('basic', 'pro')),
  status text not null check (status in ('active', 'queued', 'applied', 'expired', 'failed')),
  claimed_at timestamptz not null default now(),
  benefit_starts_at timestamptz,
  benefit_ends_at timestamptz,
  amount_off_cents integer check (amount_off_cents is null or amount_off_cents > 0),
  currency text check (currency is null or currency ~ '^[a-z]{3}$'),
  stripe_subscription_id text,
  stripe_coupon_id text,
  stripe_discount_id text,
  failure_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists birthday_reward_claims_user_claimed_idx
  on public.birthday_reward_claims (user_id, claimed_at desc);

create index if not exists birthday_reward_claims_queued_idx
  on public.birthday_reward_claims (user_id, status)
  where status = 'queued';

create table if not exists public.birthday_reward_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in (
    'birthday_set',
    'birthday_changed',
    'support_override',
    'reward_claimed',
    'reward_applied',
    'reward_queued',
    'reward_failed'
  )),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists birthday_reward_events_user_created_idx
  on public.birthday_reward_events (user_id, created_at desc);

alter table public.birthday_profiles enable row level security;
alter table public.birthday_reward_claims enable row level security;
alter table public.birthday_reward_events enable row level security;

-- All reads and writes go through the authenticated birthday-rewards Edge
-- Function. This keeps cooldowns, plan selection, claims, and audit entries
-- server-authoritative and prevents owners or team members from editing them.
revoke all on table public.birthday_profiles from anon, authenticated;
revoke all on table public.birthday_reward_claims from anon, authenticated;
revoke all on table public.birthday_reward_events from anon, authenticated;
revoke all on sequence public.birthday_reward_events_id_seq from anon, authenticated;

grant all on table public.birthday_profiles to service_role;
grant all on table public.birthday_reward_claims to service_role;
grant select, insert on table public.birthday_reward_events to service_role;
grant usage, select on sequence public.birthday_reward_events_id_seq to service_role;

comment on table public.birthday_profiles is
  'Optional month/day birthday preference for account-owner greetings and annual rewards; no birth year.';
comment on table public.birthday_reward_claims is
  'Server-authoritative rolling-365-day birthday reward claims and fulfillment state.';
comment on table public.birthday_reward_events is
  'Immutable audit history for birthday changes and reward fulfillment.';

create or replace function public.quotedr_claim_birthday_reward(
  p_user_id uuid,
  p_reward_type text,
  p_eligible_plan text,
  p_status text,
  p_benefit_starts_at timestamptz default null,
  p_benefit_ends_at timestamptz default null,
  p_amount_off_cents integer default null,
  p_currency text default null,
  p_stripe_subscription_id text default null
)
returns public.birthday_reward_claims
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_recent public.birthday_reward_claims;
  v_claim public.birthday_reward_claims;
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_user_id::text, 8242026));

  select * into v_recent
  from public.birthday_reward_claims
  where user_id = p_user_id
    and claimed_at > pg_catalog.now() - interval '365 days'
  order by claimed_at desc
  limit 1;

  if v_recent.id is not null then
    return v_recent;
  end if;

  insert into public.birthday_reward_claims (
    user_id,
    reward_type,
    eligible_plan,
    status,
    benefit_starts_at,
    benefit_ends_at,
    amount_off_cents,
    currency,
    stripe_subscription_id
  ) values (
    p_user_id,
    p_reward_type,
    p_eligible_plan,
    p_status,
    p_benefit_starts_at,
    p_benefit_ends_at,
    p_amount_off_cents,
    p_currency,
    p_stripe_subscription_id
  ) returning * into v_claim;

  return v_claim;
end;
$$;

revoke all on function public.quotedr_claim_birthday_reward(
  uuid, text, text, text, timestamptz, timestamptz, integer, text, text
) from public, anon, authenticated;
grant execute on function public.quotedr_claim_birthday_reward(
  uuid, text, text, text, timestamptz, timestamptz, integer, text, text
) to service_role;

-- Subscription state is readable by its owner but is written only by trusted
-- Stripe/server paths. The general user_data owner policy must not let a
-- browser forge the paid plan used by birthday eligibility or feature gates.
drop policy if exists quotedr_subscription_status_insert_server_only on public.user_data;
create policy quotedr_subscription_status_insert_server_only
on public.user_data as restrictive for insert to authenticated
with check (key <> 'subscription_status');

drop policy if exists quotedr_subscription_status_update_server_only on public.user_data;
create policy quotedr_subscription_status_update_server_only
on public.user_data as restrictive for update to authenticated
using (key <> 'subscription_status')
with check (key <> 'subscription_status');

drop policy if exists quotedr_subscription_status_delete_server_only on public.user_data;
create policy quotedr_subscription_status_delete_server_only
on public.user_data as restrictive for delete to authenticated
using (key <> 'subscription_status');
